[pytest]
testpaths = tests
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
addopts = --cov=dshell --cov-report=xml --cov-report=term-missing
filterwarnings =
    ignore::DeprecationWarning
