sonar.projectKey=COG-GTM_USArmy-Dshell
sonar.projectName=USArmy-Dshell
sonar.projectVersion=3.2.3
sonar.sources=dshell
sonar.language=py
sonar.python.version=3.9
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/test_*, **/tests/**
