sonar.projectKey=COG-GTM_USArmy-Dshell
sonar.projectName=Dshell
sonar.projectVersion=3.2.3
sonar.sources=dshell
sonar.tests=tests
sonar.language=py
sonar.python.version=3.10
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.bandit.reportPaths=bandit-report.json
sonar.python.pylint.reportPaths=pylint-report.txt
sonar.exclusions=**/test_*.py,**/data/**
